package br.com.marinas.produto.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="produto")
public class Produto {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String produtoId;

    @DynamoDBAttribute
    private String nome;

    @DynamoDBAttribute
    private String preco;

    public String getProdutoId() {
        return produtoId;
    }

    public String getNome() {
        return nome;
    }

    public String getPreco() {
        return preco;
    }

    public void setProdutoId(String produtoId) {
        this.produtoId = produtoId;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public void setPreco(String preco) {
        this.preco = preco;
    }

    public Produto(String produtoId, String nome, String preco) {
        this.produtoId = produtoId;
        this.nome = nome;
        this.preco = preco;
    }

    public Produto() {
    }

}
